{% set name = "boost_mp11" %}
{% set version = "1.87.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boostorg/mp11/archive/refs/tags/boost-{{ version }}.tar.gz
  sha256: f07a7282a4b440ff9f2917224badd4c112affede946ae25fba6b3e3538a858de

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  run_constrained:
    # Cannot be installed at the same time as boost-cpp as it clobbers the mp11 headers
    - boost-cpp <0a0

test:
  commands:
    - test -f $PREFIX/include/boost/mp11.hpp  # [unix]
    - if not exist %LIBRARY_INC%\\boost\\mp11.hpp exit 1  # [win]

about:
  home: https://github.com/boostorg/mp11
  summary: C++11 metaprogramming library
  license: BSL-1.0
  license_file: LICENSE_1_0.txt

extra:
  recipe-maintainers:
    - xhochy
