schema_version: 1

context:
  name: boost_mp11
  version: "1.92.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/boostorg/mp11/archive/refs/tags/boost-${{ version }}.tar.gz
  sha256: a5754dc5ff9e7ff34119983889530e3ab8d8fb43ce2b4fea9c18673044df45d9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_constraints:
    - boost-cpp <0a0

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/include/boost/mp11.hpp
      - if: win
        then: if not exist %LIBRARY_INC%\\boost\\mp11.hpp exit 1

about:
  summary: C++11 metaprogramming library
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  homepage: https://github.com/boostorg/mp11

extra:
  recipe-maintainers:
    - xhochy
